import './PlaylistForm.scss'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useImages } from '../../Contexts/ImagesContext'

const COVER_MODE_DETAILS = {
  auto: {
    label: 'Automatic',
    eyebrow: 'Curated by Elevate',
    description: 'Generates a cover based on the strongest songs in the playlist.'
  },
  'suggested-collage': {
    label: 'Suggested collage',
    eyebrow: 'Manual selection',
    description: 'Combines four suggested covers to create a more distinctive cover.'
  },
  'local-image': {
    label: 'Local image',
    eyebrow: 'Your own file',
    description: 'Use an image saved on your computer to personalize the cover.'
  },
  'remote-image': {
    label: 'Remote URL',
    eyebrow: 'From the web',
    description: 'Validate an online image and use it as the final playlist cover.'
  }
}

function resolveSuggestedCoverUrl(cover, getCollectionCoverUrl) {
  if (cover?.picture?.[0]?.data) {
    const coverKey =
      cover.suggestedId || cover.filePath || cover.coverHash || cover.title || 'suggested'
    return getCollectionCoverUrl(`suggested-cover:${coverKey}`, cover.picture[0])
  }

  return null
}

function formatAssetLabel(value, fallback = 'Selected image') {
  if (!value) {
    return ''
  }

  if (value.startsWith('data:')) {
    const mimeType = value.slice(5, value.indexOf(';')) || 'image'
    const shortType = mimeType.replace('image/', '')
    return `${fallback} (${shortType.toUpperCase()})`
  }

  const normalizedValue = value.replace(/\\/g, '/')
  const segments = normalizedValue.split('/')
  return segments[segments.length - 1] || fallback
}

const PlaylistForm = ({
  playlist,
  suggestedCovers = [],
  coverConfig = {},
  automaticCover,
  effectiveCover,
  onUpdate,
  close
}) => {
  const { ensurePlaylistAutoCover, getCachedCollectionCoverUrl, getCollectionCoverUrl } = useImages()
  const initialCoverMode = coverConfig?.customCoverMode || 'auto'
  const initialSelectedIds = Array.isArray(coverConfig?.customCoverSelection)
    ? coverConfig.customCoverSelection
        .map((selection) =>
          typeof selection === 'string'
            ? selection
            : selection?.suggestedId || selection?.filePath || selection?.coverHash || null
        )
        .filter(Boolean)
    : []

  const [nombre, setNombre] = useState(playlist?.nombre || '')
  const [coverMode, setCoverMode] = useState(initialCoverMode)
  const [selectedSuggestedCoverIds, setSelectedSuggestedCoverIds] = useState(initialSelectedIds)
  const [localImageValue, setLocalImageValue] = useState('')
  const [localResolvedUrl, setLocalResolvedUrl] = useState('')
  const [localPreviewUrl, setLocalPreviewUrl] = useState('')
  const [remoteImageValue, setRemoteImageValue] = useState('')
  const [remoteResolvedUrl, setRemoteResolvedUrl] = useState('')
  const [remotePreviewUrl, setRemotePreviewUrl] = useState('')
  const [errorMessage, setErrorMessage] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [isResolvingLocal, setIsResolvingLocal] = useState(false)
  const [isResolvingRemote, setIsResolvingRemote] = useState(false)
  const [autoGeneratedCoverUrl, setAutoGeneratedCoverUrl] = useState('')
  const [isGeneratingAutoCover, setIsGeneratingAutoCover] = useState(false)

  useEffect(() => {
    setNombre(playlist?.nombre || '')
  }, [playlist?.nombre])

  useEffect(() => {
    const nextMode = coverConfig?.customCoverMode || 'auto'
    const nextSelectedIds = Array.isArray(coverConfig?.customCoverSelection)
      ? coverConfig.customCoverSelection
          .map((selection) =>
            typeof selection === 'string'
              ? selection
              : selection?.suggestedId || selection?.filePath || selection?.coverHash || null
          )
          .filter(Boolean)
      : []

    setCoverMode(nextMode)
    setSelectedSuggestedCoverIds(nextSelectedIds)

    if (nextMode === 'local-image') {
      setLocalImageValue(coverConfig?.customCoverValue || '')
      setLocalResolvedUrl('')
      setLocalPreviewUrl('')
      setRemoteImageValue('')
      setRemoteResolvedUrl('')
      setRemotePreviewUrl('')
    } else if (nextMode === 'remote-image') {
      setRemoteImageValue(coverConfig?.customCoverValue || '')
      setRemoteResolvedUrl('')
      setRemotePreviewUrl('')
      setLocalImageValue('')
      setLocalResolvedUrl('')
      setLocalPreviewUrl('')
    } else {
      setLocalImageValue('')
      setLocalResolvedUrl('')
      setLocalPreviewUrl('')
      setRemoteImageValue('')
      setRemoteResolvedUrl('')
      setRemotePreviewUrl('')
    }
  }, [coverConfig])

  const automaticCoverUrl = automaticCover
    ? getCollectionCoverUrl(`${playlist?.path}:auto`, automaticCover)
    : ''
  const effectiveCoverUrl = effectiveCover
    ? getCollectionCoverUrl(`${playlist?.path}:effective`, effectiveCover)
    : ''
  const playlistAutoCoverKey = playlist?.path ? `playlist:auto:${playlist.path}` : ''
  const playlistAutoCoverSignature = coverConfig?.customCoverHash || ''
  const hasCustomCoverMode = ['suggested-collage', 'local-image', 'remote-image'].includes(
    coverConfig?.customCoverMode
  )

  useEffect(() => {
    let alive = true

    if (!playlist?.path || hasCustomCoverMode || effectiveCoverUrl || automaticCoverUrl) {
      setAutoGeneratedCoverUrl('')
      setIsGeneratingAutoCover(false)
      return () => {
        alive = false
      }
    }

    const cachedCoverUrl = getCachedCollectionCoverUrl(
      playlistAutoCoverKey,
      playlistAutoCoverSignature || undefined
    )
    if (cachedCoverUrl) {
      setAutoGeneratedCoverUrl(cachedCoverUrl)
      setIsGeneratingAutoCover(false)
      return () => {
        alive = false
      }
    }

    setIsGeneratingAutoCover(true)
    ensurePlaylistAutoCover(playlist.path, {
      coverKey: playlistAutoCoverKey,
      signature: playlistAutoCoverSignature || playlistAutoCoverKey
    }).then((generatedCoverUrl) => {
      if (!alive) return

      setAutoGeneratedCoverUrl(generatedCoverUrl || '')
      setIsGeneratingAutoCover(false)
    })

    return () => {
      alive = false
    }
  }, [
    automaticCoverUrl,
    effectiveCoverUrl,
    ensurePlaylistAutoCover,
    getCachedCollectionCoverUrl,
    hasCustomCoverMode,
    playlist?.path,
    playlistAutoCoverKey,
    playlistAutoCoverSignature
  ])

  const collagePreviewUrls = useMemo(
    () =>
      selectedSuggestedCoverIds
        .map((id) => suggestedCovers.find((cover) => cover.suggestedId === id))
        .filter(Boolean)
        .map((cover) => resolveSuggestedCoverUrl(cover, getCollectionCoverUrl))
        .filter(Boolean),
    [getCollectionCoverUrl, selectedSuggestedCoverIds, suggestedCovers]
  )

  const activeModeDetails = COVER_MODE_DETAILS[coverMode] || COVER_MODE_DETAILS.auto
  const localAssetLabel = formatAssetLabel(localImageValue || localResolvedUrl, 'Local image')
  const remoteAssetLabel = formatAssetLabel(remoteImageValue || remoteResolvedUrl, 'Remote image')
  const currentPreviewUrl =
    (coverMode === 'local-image' && localPreviewUrl) ||
    (coverMode === 'remote-image' && remotePreviewUrl) ||
    effectiveCoverUrl ||
    automaticCoverUrl ||
    autoGeneratedCoverUrl
  const autoCoverStatusLabel = isGeneratingAutoCover
    ? 'Generating automatic cover...'
    : autoGeneratedCoverUrl
      ? 'Cached automatic cover'
      : automaticCoverUrl
        ? 'Based on your current collection'
        : 'It will be generated when enough material is available'

  const handleCoverModeChange = useCallback((nextMode) => {
    setCoverMode(nextMode)
    setErrorMessage('')
  }, [])

  const handleSuggestedCoverClick = useCallback((cover) => {
    const selectedId = cover.suggestedId

    setSelectedSuggestedCoverIds((previous) => {
      if (previous.includes(selectedId)) {
        return previous.filter((id) => id !== selectedId)
      }

      if (previous.length >= 4) {
        setErrorMessage('Select exactly 4 images')
        return previous
      }

      setErrorMessage('')
      return [...previous, selectedId]
    })
  }, [])

  const handleLocalImageSelect = useCallback(async () => {
    setIsResolvingLocal(true)
    setErrorMessage('')

    try {
      const result = await window.electron.imageSources.pickLocal()
      if (result?.success) {
        setLocalImageValue(result.filePath || '')
        setLocalResolvedUrl(result.resolvedUrl || '')
        setLocalPreviewUrl(result.resolvedUrl || '')
      } else if (result?.errorCode !== 'canceled') {
        setErrorMessage(result?.errorMessage || 'Could not select the image')
      }
    } catch (error) {
      console.error('Error picking local image:', error)
      setErrorMessage('Could not select the image')
    } finally {
      setIsResolvingLocal(false)
    }
  }, [])

  const handleRemoteImageApply = useCallback(async () => {
    const url = remoteImageValue.trim()
    if (!url) {
      setErrorMessage('Enter a valid URL')
      return
    }

    setIsResolvingRemote(true)
    setErrorMessage('')

    try {
      const result = await window.electron.imageSources.validateRemote(url)
      if (result?.success) {
        setRemoteResolvedUrl(result.resolvedUrl || '')
        setRemotePreviewUrl(result.resolvedUrl || '')
      } else {
        setErrorMessage(result?.errorMessage || 'Could not validate the remote image')
      }
    } catch (error) {
      console.error('Error validating remote image:', error)
      setErrorMessage('Could not validate the remote image')
    } finally {
      setIsResolvingRemote(false)
    }
  }, [remoteImageValue])

  const handleResetCover = useCallback(() => {
    setCoverMode('auto')
    setSelectedSuggestedCoverIds([])
    setLocalImageValue('')
    setLocalResolvedUrl('')
    setLocalPreviewUrl('')
    setRemoteImageValue('')
    setRemoteResolvedUrl('')
    setRemotePreviewUrl('')
    setErrorMessage('')
  }, [])

  const validateForm = useCallback(() => {
    if (!nombre.trim()) {
      setErrorMessage('Name cannot be empty')
      return false
    }

    if (coverMode === 'suggested-collage' && selectedSuggestedCoverIds.length !== 4) {
      setErrorMessage('Select exactly 4 images for the collage')
      return false
    }

    if (coverMode === 'local-image' && !localResolvedUrl) {
      setErrorMessage('Select a valid local image')
      return false
    }

    if (coverMode === 'remote-image' && !remoteResolvedUrl) {
      setErrorMessage('Validate an image URL before saving')
      return false
    }

    return true
  }, [coverMode, localResolvedUrl, nombre, remoteResolvedUrl, selectedSuggestedCoverIds.length])

  const handleSubmit = useCallback(
    async (event) => {
      event.preventDefault()
      setErrorMessage('')

      if (!validateForm()) {
        return
      }

      setIsSubmitting(true)

      const payload = {
        nombre: nombre.trim()
      }

      if (coverMode === 'suggested-collage') {
        payload.coverMode = 'suggested-collage'
        payload.coverSelection = selectedSuggestedCoverIds
      } else if (coverMode === 'local-image') {
        payload.coverMode = 'local-image'
        payload.coverValue = localImageValue
      } else if (coverMode === 'remote-image') {
        payload.coverMode = 'remote-image'
        payload.coverValue = remoteImageValue.trim()
      } else {
        payload.coverMode = 'auto'
      }

      try {
        const response = await onUpdate(playlist.path, payload)
        if (response?.success) {
          close()
        } else {
          setErrorMessage(response?.error || 'Error saving')
        }
      } finally {
        setIsSubmitting(false)
      }
    },
    [
      close,
      coverMode,
      localResolvedUrl,
      nombre,
      onUpdate,
      playlist.path,
      remoteResolvedUrl,
      selectedSuggestedCoverIds,
      validateForm
    ]
  )

  return (
    <form onSubmit={handleSubmit} className="playlist-form">
      <div className="playlist-form__header">
        <div>
          <span className="playlist-form__eyebrow">Playlist editor</span>
        </div>
        <div className="playlist-form__header-badge">{activeModeDetails.label}</div>
      </div>

      <div className="playlist-form__body">
        <div className="playlist-form__layout">
          <section className="playlist-form__panel playlist-form__panel--details">
            <div className="playlist-form__field">
              <label className="playlist-form__label">Name</label>

              <input
                type="text"
                value={nombre}
                onChange={(event) => setNombre(event.target.value)}
                className="playlist-form__input"
                placeholder="Playlist name"
              />
            </div>

            <div className="playlist-form__field">
              <label className="playlist-form__label">Location</label>
              <div className="playlist-form__path-card">
                <span className="playlist-form__path-kicker">Linked path</span>
                <strong>{playlist?.path || 'No path available'}</strong>
              </div>
            </div>

            <div className="playlist-form__summary-card">
              <div className="playlist-form__summary-art">
                {coverMode === 'suggested-collage' && collagePreviewUrls.length > 0 ? (
                  <div className="playlist-form__summary-collage">
                    {collagePreviewUrls.map((image, index) => (
                      <img key={`${image}-${index}`} src={image} alt={`Preview ${index + 1}`} />
                    ))}
                  </div>
                ) : currentPreviewUrl ? (
                  <img src={currentPreviewUrl} alt="Cover preview" />
                ) : (
                  <div className="playlist-form__summary-empty">No cover</div>
                )}
              </div>

              <div className="playlist-form__summary-copy">
                <span>{activeModeDetails.eyebrow}</span>
                <h3>{activeModeDetails.label}</h3>
                <p>{activeModeDetails.description}</p>
                <div className="playlist-form__summary-meta">
                  <strong>
                    {coverMode === 'auto' ? 'Automatic cover' : 'Custom cover active'}
                  </strong>
                  <small>
                    {coverMode === 'suggested-collage'
                      ? `${selectedSuggestedCoverIds.length}/4 images selected`
                      : coverMode === 'local-image'
                        ? localAssetLabel || 'You have not chosen a file yet'
                        : coverMode === 'remote-image'
                          ? remoteAssetLabel || 'You have not validated a URL yet'
                          : autoCoverStatusLabel}
                  </small>
                </div>
              </div>
            </div>
          </section>

          <section className="playlist-form__panel playlist-form__panel--cover">
            <div className="playlist-form__section-header">
              <div>
                <label className="playlist-form__label">Cover</label>
              </div>
              <button type="button" className="playlist-form__ghost-btn" onClick={handleResetCover}>
                Reset
              </button>
            </div>

            <div className="playlist-form__cover-modes">
              {Object.entries(COVER_MODE_DETAILS).map(([modeKey, details]) => (
                <button
                  key={modeKey}
                  type="button"
                  className={`playlist-form__mode-btn ${coverMode === modeKey ? 'playlist-form__mode-btn--active' : ''}`}
                  onClick={() => handleCoverModeChange(modeKey)}
                  aria-pressed={coverMode === modeKey}
                >
                  <span>{details.eyebrow}</span>
                  <strong>{details.label}</strong>
                </button>
              ))}
            </div>

            {coverMode === 'auto' && (
              <div className="playlist-form__cover-preview">
                <p className="playlist-form__cover-info">
                  The automatic cover will be based on the most played songs.
                </p>
                {automaticCoverUrl ? (
                  <div className="playlist-form__cover-current">
                    <img src={automaticCoverUrl} alt="Automatic cover" />
                  </div>
                ) : autoGeneratedCoverUrl ? (
                  <div className="playlist-form__cover-current">
                    <img src={autoGeneratedCoverUrl} alt="Automatic cover" />
                  </div>
                ) : isGeneratingAutoCover ? (
                  <div className="playlist-form__cover-empty">Generating automatic cover...</div>
                ) : (
                  <div className="playlist-form__cover-empty">
                    No automatic cover is available for this playlist yet.
                  </div>
                )}
              </div>
            )}

            {coverMode === 'suggested-collage' && (
              <div className="playlist-form__suggested">
                <p className="playlist-form__cover-info">
                  Select exactly 4 images to build the collage (
                  {selectedSuggestedCoverIds.length}/4)
                </p>

                {suggestedCovers.length > 0 ? (
                  <div className="playlist-form__suggested-grid">
                    {suggestedCovers.map((cover) => {
                      const isSelected = selectedSuggestedCoverIds.includes(cover.suggestedId)
                      const coverUrl = resolveSuggestedCoverUrl(cover, getCollectionCoverUrl)

                      return (
                        <button
                          key={cover.suggestedId}
                          type="button"
                          className={`playlist-form__suggested-item ${isSelected ? 'playlist-form__suggested-item--selected' : ''}`}
                          onClick={() => handleSuggestedCoverClick(cover)}
                        >
                          {coverUrl ? (
                            <img src={coverUrl} alt={cover.title || 'Cover'} />
                          ) : (
                            <div className="playlist-form__suggested-placeholder">No cover</div>
                          )}
                          <div className="playlist-form__suggested-info">
                            <span className="playlist-form__suggested-title">
                              {cover.title || 'Untitled'}
                            </span>
                            {cover.artist ? (
                              <span className="playlist-form__suggested-artist">
                                {cover.artist}
                              </span>
                            ) : null}
                          </div>
                          {isSelected ? (
                            <div className="playlist-form__suggested-check">OK</div>
                          ) : null}
                        </button>
                      )
                    })}
                  </div>
                ) : (
                  <p className="playlist-form__cover-info">
                    There are not enough covers available to create a collage.
                  </p>
                )}

                {selectedSuggestedCoverIds.length > 0 ? (
                  <div className="playlist-form__selected-info">
                    <p>Selected: {selectedSuggestedCoverIds.length}/4</p>
                    <button
                      type="button"
                      className="playlist-form__ghost-btn"
                      onClick={() => setSelectedSuggestedCoverIds([])}
                    >
                      Clear selection
                    </button>
                  </div>
                ) : null}
              </div>
            )}

            {coverMode === 'local-image' && (
              <div className="playlist-form__local">
                <div className="playlist-form__picker-copy">
                  <span>Local file</span>
                  <p>
                    Choose a square image, or one with a strong crop, to keep the cover clean.
                  </p>
                </div>
                <button
                  type="button"
                  className="playlist-form__select-btn"
                  onClick={handleLocalImageSelect}
                  disabled={isResolvingLocal}
                >
                  {isResolvingLocal ? 'Loading image...' : 'Choose image'}
                </button>
                {localAssetLabel ? (
                  <code className="playlist-form__asset-pill">{localAssetLabel}</code>
                ) : null}
                {localPreviewUrl ? (
                  <div className="playlist-form__local-preview">
                    <img src={localPreviewUrl} alt="Preview local" />
                    <button
                      type="button"
                      className="playlist-form__ghost-btn"
                      onClick={() => {
                        setLocalImageValue('')
                        setLocalResolvedUrl('')
                        setLocalPreviewUrl('')
                      }}
                    >
                      Delete
                    </button>
                  </div>
                ) : null}
              </div>
            )}

            {coverMode === 'remote-image' && (
              <div className="playlist-form__remote">
                <div className="playlist-form__picker-copy">
                  <span>Remote image</span>
                  <p>Paste a direct URL and validate it before saving to avoid broken links.</p>
                </div>
                <div className="playlist-form__remote-input-group">
                  <input
                    type="text"
                    value={remoteImageValue}
                    onChange={(event) => {
                      setRemoteImageValue(event.target.value)
                      setRemoteResolvedUrl('')
                      setRemotePreviewUrl('')
                    }}
                    placeholder="https://example.com/image.jpg"
                    className="playlist-form__input"
                  />
                  <button
                    type="button"
                    className="playlist-form__apply-btn"
                    onClick={handleRemoteImageApply}
                    disabled={isResolvingRemote}
                  >
                    {isResolvingRemote ? 'Validating...' : 'Validate URL'}
                  </button>
                </div>
                {remoteAssetLabel ? (
                  <code className="playlist-form__asset-pill">{remoteAssetLabel}</code>
                ) : null}
                {remotePreviewUrl ? (
                  <div className="playlist-form__remote-preview">
                    <img src={remotePreviewUrl} alt="Preview remota" />
                    <button
                      type="button"
                      className="playlist-form__ghost-btn"
                      onClick={() => {
                        setRemoteImageValue('')
                        setRemoteResolvedUrl('')
                        setRemotePreviewUrl('')
                      }}
                    >
                      Delete
                    </button>
                  </div>
                ) : null}
              </div>
            )}
          </section>
        </div>

        {errorMessage ? <div className="playlist-form__error">{errorMessage}</div> : null}
      </div>

      <div className="playlist-form__actions">
        <button type="button" className="playlist-form__cancel-btn" onClick={close}>
          Cancel
        </button>
        <button type="submit" className="playlist-form__submit-btn" disabled={isSubmitting}>
          {isSubmitting ? 'Saving...' : 'Save changes'}
        </button>
      </div>
    </form>
  )
}

export default PlaylistForm
