import './PlaylistForm.scss'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useImages } from '../../Contexts/ImagesContext'

const COVER_MODE_DETAILS = {
  auto: {
    label: 'Automatica',
    eyebrow: 'Curada por Elevate',
    description: 'Genera una portada basada en las canciones con mas peso dentro de la playlist.'
  },
  'suggested-collage': {
    label: 'Collage sugerido',
    eyebrow: 'Seleccion manual',
    description: 'Combina cuatro covers sugeridos para construir una portada con mas identidad.'
  },
  'local-image': {
    label: 'Imagen local',
    eyebrow: 'Archivo propio',
    description: 'Usa una imagen guardada en tu equipo para personalizar la portada.'
  },
  'remote-image': {
    label: 'URL remota',
    eyebrow: 'Desde la web',
    description: 'Valida una imagen online y usala como portada final de la playlist.'
  }
}

function resolveSuggestedCoverUrl(cover, getCollectionCoverUrl) {
  if (cover?.picture?.[0]?.data) {
    const coverKey =
      cover.suggestedId || cover.filePath || cover.coverHash || cover.title || 'suggested'
    return getCollectionCoverUrl(`suggested-cover:${coverKey}`, cover.picture[0])
  }

  return null
}

function formatAssetLabel(value, fallback = 'Imagen seleccionada') {
  if (!value) {
    return ''
  }

  if (value.startsWith('data:')) {
    const mimeType = value.slice(5, value.indexOf(';')) || 'image'
    const shortType = mimeType.replace('image/', '')
    return `${fallback} (${shortType.toUpperCase()})`
  }

  const normalizedValue = value.replace(/\\/g, '/')
  const segments = normalizedValue.split('/')
  return segments[segments.length - 1] || fallback
}

const PlaylistForm = ({
  playlist,
  suggestedCovers = [],
  coverConfig = {},
  automaticCover,
  effectiveCover,
  onUpdate,
  close
}) => {
  const { ensurePlaylistAutoCover, getCachedCollectionCoverUrl, getCollectionCoverUrl } = useImages()
  const initialCoverMode = coverConfig?.customCoverMode || 'auto'
  const initialSelectedIds = Array.isArray(coverConfig?.customCoverSelection)
    ? coverConfig.customCoverSelection
        .map((selection) =>
          typeof selection === 'string'
            ? selection
            : selection?.suggestedId || selection?.filePath || selection?.coverHash || null
        )
        .filter(Boolean)
    : []

  const [nombre, setNombre] = useState(playlist?.nombre || '')
  const [coverMode, setCoverMode] = useState(initialCoverMode)
  const [selectedSuggestedCoverIds, setSelectedSuggestedCoverIds] = useState(initialSelectedIds)
  const [localImageValue, setLocalImageValue] = useState('')
  const [localResolvedUrl, setLocalResolvedUrl] = useState('')
  const [localPreviewUrl, setLocalPreviewUrl] = useState('')
  const [remoteImageValue, setRemoteImageValue] = useState('')
  const [remoteResolvedUrl, setRemoteResolvedUrl] = useState('')
  const [remotePreviewUrl, setRemotePreviewUrl] = useState('')
  const [errorMessage, setErrorMessage] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [isResolvingLocal, setIsResolvingLocal] = useState(false)
  const [isResolvingRemote, setIsResolvingRemote] = useState(false)
  const [autoGeneratedCoverUrl, setAutoGeneratedCoverUrl] = useState('')
  const [isGeneratingAutoCover, setIsGeneratingAutoCover] = useState(false)

  useEffect(() => {
    setNombre(playlist?.nombre || '')
  }, [playlist?.nombre])

  useEffect(() => {
    const nextMode = coverConfig?.customCoverMode || 'auto'
    const nextSelectedIds = Array.isArray(coverConfig?.customCoverSelection)
      ? coverConfig.customCoverSelection
          .map((selection) =>
            typeof selection === 'string'
              ? selection
              : selection?.suggestedId || selection?.filePath || selection?.coverHash || null
          )
          .filter(Boolean)
      : []

    setCoverMode(nextMode)
    setSelectedSuggestedCoverIds(nextSelectedIds)

    if (nextMode === 'local-image') {
      setLocalImageValue(coverConfig?.customCoverValue || '')
      setLocalResolvedUrl('')
      setLocalPreviewUrl('')
      setRemoteImageValue('')
      setRemoteResolvedUrl('')
      setRemotePreviewUrl('')
    } else if (nextMode === 'remote-image') {
      setRemoteImageValue(coverConfig?.customCoverValue || '')
      setRemoteResolvedUrl('')
      setRemotePreviewUrl('')
      setLocalImageValue('')
      setLocalResolvedUrl('')
      setLocalPreviewUrl('')
    } else {
      setLocalImageValue('')
      setLocalResolvedUrl('')
      setLocalPreviewUrl('')
      setRemoteImageValue('')
      setRemoteResolvedUrl('')
      setRemotePreviewUrl('')
    }
  }, [coverConfig])

  const automaticCoverUrl = automaticCover
    ? getCollectionCoverUrl(`${playlist?.path}:auto`, automaticCover)
    : ''
  const effectiveCoverUrl = effectiveCover
    ? getCollectionCoverUrl(`${playlist?.path}:effective`, effectiveCover)
    : ''
  const playlistAutoCoverKey = playlist?.path ? `playlist:auto:${playlist.path}` : ''
  const playlistAutoCoverSignature = coverConfig?.customCoverHash || ''
  const hasCustomCoverMode = ['suggested-collage', 'local-image', 'remote-image'].includes(
    coverConfig?.customCoverMode
  )

  useEffect(() => {
    let alive = true

    if (!playlist?.path || hasCustomCoverMode || effectiveCoverUrl || automaticCoverUrl) {
      setAutoGeneratedCoverUrl('')
      setIsGeneratingAutoCover(false)
      return () => {
        alive = false
      }
    }

    const cachedCoverUrl = getCachedCollectionCoverUrl(
      playlistAutoCoverKey,
      playlistAutoCoverSignature || undefined
    )
    if (cachedCoverUrl) {
      setAutoGeneratedCoverUrl(cachedCoverUrl)
      setIsGeneratingAutoCover(false)
      return () => {
        alive = false
      }
    }

    setIsGeneratingAutoCover(true)
    ensurePlaylistAutoCover(playlist.path, {
      coverKey: playlistAutoCoverKey,
      signature: playlistAutoCoverSignature || playlistAutoCoverKey
    }).then((generatedCoverUrl) => {
      if (!alive) return

      setAutoGeneratedCoverUrl(generatedCoverUrl || '')
      setIsGeneratingAutoCover(false)
    })

    return () => {
      alive = false
    }
  }, [
    automaticCoverUrl,
    effectiveCoverUrl,
    ensurePlaylistAutoCover,
    getCachedCollectionCoverUrl,
    hasCustomCoverMode,
    playlist?.path,
    playlistAutoCoverKey,
    playlistAutoCoverSignature
  ])

  const collagePreviewUrls = useMemo(
    () =>
      selectedSuggestedCoverIds
        .map((id) => suggestedCovers.find((cover) => cover.suggestedId === id))
        .filter(Boolean)
        .map((cover) => resolveSuggestedCoverUrl(cover, getCollectionCoverUrl))
        .filter(Boolean),
    [getCollectionCoverUrl, selectedSuggestedCoverIds, suggestedCovers]
  )

  const activeModeDetails = COVER_MODE_DETAILS[coverMode] || COVER_MODE_DETAILS.auto
  const localAssetLabel = formatAssetLabel(localImageValue || localResolvedUrl, 'Imagen local')
  const remoteAssetLabel = formatAssetLabel(remoteImageValue || remoteResolvedUrl, 'Imagen remota')
  const currentPreviewUrl =
    (coverMode === 'local-image' && localPreviewUrl) ||
    (coverMode === 'remote-image' && remotePreviewUrl) ||
    effectiveCoverUrl ||
    automaticCoverUrl ||
    autoGeneratedCoverUrl
  const autoCoverStatusLabel = isGeneratingAutoCover
    ? 'Generando portada automatica...'
    : autoGeneratedCoverUrl
      ? 'Portada automatica cacheada'
      : automaticCoverUrl
        ? 'Basada en tu coleccion actual'
        : 'Se generara cuando haya material disponible'

  const handleCoverModeChange = useCallback((nextMode) => {
    setCoverMode(nextMode)
    setErrorMessage('')
  }, [])

  const handleSuggestedCoverClick = useCallback((cover) => {
    const selectedId = cover.suggestedId

    setSelectedSuggestedCoverIds((previous) => {
      if (previous.includes(selectedId)) {
        return previous.filter((id) => id !== selectedId)
      }

      if (previous.length >= 4) {
        setErrorMessage('Selecciona solo 4 imagenes')
        return previous
      }

      setErrorMessage('')
      return [...previous, selectedId]
    })
  }, [])

  const handleLocalImageSelect = useCallback(async () => {
    setIsResolvingLocal(true)
    setErrorMessage('')

    try {
      const result = await window.electron.imageSources.pickLocal()
      if (result?.success) {
        setLocalImageValue(result.filePath || '')
        setLocalResolvedUrl(result.resolvedUrl || '')
        setLocalPreviewUrl(result.resolvedUrl || '')
      } else if (result?.errorCode !== 'canceled') {
        setErrorMessage(result?.errorMessage || 'No se pudo seleccionar la imagen')
      }
    } catch (error) {
      console.error('Error picking local image:', error)
      setErrorMessage('No se pudo seleccionar la imagen')
    } finally {
      setIsResolvingLocal(false)
    }
  }, [])

  const handleRemoteImageApply = useCallback(async () => {
    const url = remoteImageValue.trim()
    if (!url) {
      setErrorMessage('Introduce una URL valida')
      return
    }

    setIsResolvingRemote(true)
    setErrorMessage('')

    try {
      const result = await window.electron.imageSources.validateRemote(url)
      if (result?.success) {
        setRemoteResolvedUrl(result.resolvedUrl || '')
        setRemotePreviewUrl(result.resolvedUrl || '')
      } else {
        setErrorMessage(result?.errorMessage || 'No se pudo validar la imagen remota')
      }
    } catch (error) {
      console.error('Error validating remote image:', error)
      setErrorMessage('No se pudo validar la imagen remota')
    } finally {
      setIsResolvingRemote(false)
    }
  }, [remoteImageValue])

  const handleResetCover = useCallback(() => {
    setCoverMode('auto')
    setSelectedSuggestedCoverIds([])
    setLocalImageValue('')
    setLocalResolvedUrl('')
    setLocalPreviewUrl('')
    setRemoteImageValue('')
    setRemoteResolvedUrl('')
    setRemotePreviewUrl('')
    setErrorMessage('')
  }, [])

  const validateForm = useCallback(() => {
    if (!nombre.trim()) {
      setErrorMessage('El nombre no puede estar vacio')
      return false
    }

    if (coverMode === 'suggested-collage' && selectedSuggestedCoverIds.length !== 4) {
      setErrorMessage('Selecciona exactamente 4 imagenes para el collage')
      return false
    }

    if (coverMode === 'local-image' && !localResolvedUrl) {
      setErrorMessage('Selecciona una imagen local valida')
      return false
    }

    if (coverMode === 'remote-image' && !remoteResolvedUrl) {
      setErrorMessage('Valida una URL de imagen antes de guardar')
      return false
    }

    return true
  }, [coverMode, localResolvedUrl, nombre, remoteResolvedUrl, selectedSuggestedCoverIds.length])

  const handleSubmit = useCallback(
    async (event) => {
      event.preventDefault()
      setErrorMessage('')

      if (!validateForm()) {
        return
      }

      setIsSubmitting(true)

      const payload = {
        nombre: nombre.trim()
      }

      if (coverMode === 'suggested-collage') {
        payload.coverMode = 'suggested-collage'
        payload.coverSelection = selectedSuggestedCoverIds
      } else if (coverMode === 'local-image') {
        payload.coverMode = 'local-image'
        payload.coverValue = localImageValue
      } else if (coverMode === 'remote-image') {
        payload.coverMode = 'remote-image'
        payload.coverValue = remoteImageValue.trim()
      } else {
        payload.coverMode = 'auto'
      }

      try {
        const response = await onUpdate(playlist.path, payload)
        if (response?.success) {
          close()
        } else {
          setErrorMessage(response?.error || 'Error al guardar')
        }
      } finally {
        setIsSubmitting(false)
      }
    },
    [
      close,
      coverMode,
      localResolvedUrl,
      nombre,
      onUpdate,
      playlist.path,
      remoteResolvedUrl,
      selectedSuggestedCoverIds,
      validateForm
    ]
  )

  return (
    <form onSubmit={handleSubmit} className="playlist-form">
      <div className="playlist-form__header">
        <div>
          <span className="playlist-form__eyebrow">Editor de playlist</span>
        </div>
        <div className="playlist-form__header-badge">{activeModeDetails.label}</div>
      </div>

      <div className="playlist-form__body">
        <div className="playlist-form__layout">
          <section className="playlist-form__panel playlist-form__panel--details">
            <div className="playlist-form__field">
              <label className="playlist-form__label">Nombre</label>

              <input
                type="text"
                value={nombre}
                onChange={(event) => setNombre(event.target.value)}
                className="playlist-form__input"
                placeholder="Nombre de la playlist"
              />
            </div>

            <div className="playlist-form__field">
              <label className="playlist-form__label">Ubicacion</label>
              <div className="playlist-form__path-card">
                <span className="playlist-form__path-kicker">Ruta vinculada</span>
                <strong>{playlist?.path || 'Sin ruta disponible'}</strong>
              </div>
            </div>

            <div className="playlist-form__summary-card">
              <div className="playlist-form__summary-art">
                {coverMode === 'suggested-collage' && collagePreviewUrls.length > 0 ? (
                  <div className="playlist-form__summary-collage">
                    {collagePreviewUrls.map((image, index) => (
                      <img key={`${image}-${index}`} src={image} alt={`Preview ${index + 1}`} />
                    ))}
                  </div>
                ) : currentPreviewUrl ? (
                  <img src={currentPreviewUrl} alt="Preview de portada" />
                ) : (
                  <div className="playlist-form__summary-empty">Sin portada</div>
                )}
              </div>

              <div className="playlist-form__summary-copy">
                <span>{activeModeDetails.eyebrow}</span>
                <h3>{activeModeDetails.label}</h3>
                <p>{activeModeDetails.description}</p>
                <div className="playlist-form__summary-meta">
                  <strong>
                    {coverMode === 'auto' ? 'Portada automatica' : 'Portada personalizada activa'}
                  </strong>
                  <small>
                    {coverMode === 'suggested-collage'
                      ? `${selectedSuggestedCoverIds.length}/4 imagenes seleccionadas`
                      : coverMode === 'local-image'
                        ? localAssetLabel || 'Aun no has elegido un archivo'
                        : coverMode === 'remote-image'
                          ? remoteAssetLabel || 'Aun no has validado ninguna URL'
                          : autoCoverStatusLabel}
                  </small>
                </div>
              </div>
            </div>
          </section>

          <section className="playlist-form__panel playlist-form__panel--cover">
            <div className="playlist-form__section-header">
              <div>
                <label className="playlist-form__label">Portada</label>
              </div>
              <button type="button" className="playlist-form__ghost-btn" onClick={handleResetCover}>
                Restablecer
              </button>
            </div>

            <div className="playlist-form__cover-modes">
              {Object.entries(COVER_MODE_DETAILS).map(([modeKey, details]) => (
                <button
                  key={modeKey}
                  type="button"
                  className={`playlist-form__mode-btn ${coverMode === modeKey ? 'playlist-form__mode-btn--active' : ''}`}
                  onClick={() => handleCoverModeChange(modeKey)}
                  aria-pressed={coverMode === modeKey}
                >
                  <span>{details.eyebrow}</span>
                  <strong>{details.label}</strong>
                </button>
              ))}
            </div>

            {coverMode === 'auto' && (
              <div className="playlist-form__cover-preview">
                <p className="playlist-form__cover-info">
                  Se usara la portada automatica basada en las canciones mas escuchadas.
                </p>
                {automaticCoverUrl ? (
                  <div className="playlist-form__cover-current">
                    <img src={automaticCoverUrl} alt="Cover automatico" />
                  </div>
                ) : autoGeneratedCoverUrl ? (
                  <div className="playlist-form__cover-current">
                    <img src={autoGeneratedCoverUrl} alt="Cover automatico" />
                  </div>
                ) : isGeneratingAutoCover ? (
                  <div className="playlist-form__cover-empty">Generando portada automatica...</div>
                ) : (
                  <div className="playlist-form__cover-empty">
                    Aun no hay una portada automatica disponible para esta playlist.
                  </div>
                )}
              </div>
            )}

            {coverMode === 'suggested-collage' && (
              <div className="playlist-form__suggested">
                <p className="playlist-form__cover-info">
                  Selecciona exactamente 4 imagenes para construir el collage (
                  {selectedSuggestedCoverIds.length}/4)
                </p>

                {suggestedCovers.length > 0 ? (
                  <div className="playlist-form__suggested-grid">
                    {suggestedCovers.map((cover) => {
                      const isSelected = selectedSuggestedCoverIds.includes(cover.suggestedId)
                      const coverUrl = resolveSuggestedCoverUrl(cover, getCollectionCoverUrl)

                      return (
                        <button
                          key={cover.suggestedId}
                          type="button"
                          className={`playlist-form__suggested-item ${isSelected ? 'playlist-form__suggested-item--selected' : ''}`}
                          onClick={() => handleSuggestedCoverClick(cover)}
                        >
                          {coverUrl ? (
                            <img src={coverUrl} alt={cover.title || 'Cover'} />
                          ) : (
                            <div className="playlist-form__suggested-placeholder">Sin cover</div>
                          )}
                          <div className="playlist-form__suggested-info">
                            <span className="playlist-form__suggested-title">
                              {cover.title || 'Sin titulo'}
                            </span>
                            {cover.artist ? (
                              <span className="playlist-form__suggested-artist">
                                {cover.artist}
                              </span>
                            ) : null}
                          </div>
                          {isSelected ? (
                            <div className="playlist-form__suggested-check">OK</div>
                          ) : null}
                        </button>
                      )
                    })}
                  </div>
                ) : (
                  <p className="playlist-form__cover-info">
                    No hay suficientes covers disponibles para crear un collage.
                  </p>
                )}

                {selectedSuggestedCoverIds.length > 0 ? (
                  <div className="playlist-form__selected-info">
                    <p>Seleccionadas: {selectedSuggestedCoverIds.length}/4</p>
                    <button
                      type="button"
                      className="playlist-form__ghost-btn"
                      onClick={() => setSelectedSuggestedCoverIds([])}
                    >
                      Limpiar seleccion
                    </button>
                  </div>
                ) : null}
              </div>
            )}

            {coverMode === 'local-image' && (
              <div className="playlist-form__local">
                <div className="playlist-form__picker-copy">
                  <span>Archivo local</span>
                  <p>
                    Elige una imagen cuadrada o con buen recorte para mantener una portada limpia.
                  </p>
                </div>
                <button
                  type="button"
                  className="playlist-form__select-btn"
                  onClick={handleLocalImageSelect}
                  disabled={isResolvingLocal}
                >
                  {isResolvingLocal ? 'Cargando imagen...' : 'Elegir imagen'}
                </button>
                {localAssetLabel ? (
                  <code className="playlist-form__asset-pill">{localAssetLabel}</code>
                ) : null}
                {localPreviewUrl ? (
                  <div className="playlist-form__local-preview">
                    <img src={localPreviewUrl} alt="Preview local" />
                    <button
                      type="button"
                      className="playlist-form__ghost-btn"
                      onClick={() => {
                        setLocalImageValue('')
                        setLocalResolvedUrl('')
                        setLocalPreviewUrl('')
                      }}
                    >
                      Eliminar
                    </button>
                  </div>
                ) : null}
              </div>
            )}

            {coverMode === 'remote-image' && (
              <div className="playlist-form__remote">
                <div className="playlist-form__picker-copy">
                  <span>Imagen remota</span>
                  <p>Pega una URL directa y validala antes de guardar para evitar enlaces rotos.</p>
                </div>
                <div className="playlist-form__remote-input-group">
                  <input
                    type="text"
                    value={remoteImageValue}
                    onChange={(event) => {
                      setRemoteImageValue(event.target.value)
                      setRemoteResolvedUrl('')
                      setRemotePreviewUrl('')
                    }}
                    placeholder="https://ejemplo.com/imagen.jpg"
                    className="playlist-form__input"
                  />
                  <button
                    type="button"
                    className="playlist-form__apply-btn"
                    onClick={handleRemoteImageApply}
                    disabled={isResolvingRemote}
                  >
                    {isResolvingRemote ? 'Validando...' : 'Validar URL'}
                  </button>
                </div>
                {remoteAssetLabel ? (
                  <code className="playlist-form__asset-pill">{remoteAssetLabel}</code>
                ) : null}
                {remotePreviewUrl ? (
                  <div className="playlist-form__remote-preview">
                    <img src={remotePreviewUrl} alt="Preview remota" />
                    <button
                      type="button"
                      className="playlist-form__ghost-btn"
                      onClick={() => {
                        setRemoteImageValue('')
                        setRemoteResolvedUrl('')
                        setRemotePreviewUrl('')
                      }}
                    >
                      Eliminar
                    </button>
                  </div>
                ) : null}
              </div>
            )}
          </section>
        </div>

        {errorMessage ? <div className="playlist-form__error">{errorMessage}</div> : null}
      </div>

      <div className="playlist-form__actions">
        <button type="button" className="playlist-form__cancel-btn" onClick={close}>
          Cancelar
        </button>
        <button type="submit" className="playlist-form__submit-btn" disabled={isSubmitting}>
          {isSubmitting ? 'Guardando...' : 'Guardar cambios'}
        </button>
      </div>
    </form>
  )
}

export default PlaylistForm
